### ISSUE TITLE
Add option to load model weights in half-precision

### ISSUE THREAD

**Issue by mamei16** [Saganaki22/StableAudioWebUI#1]
To save some VRAM and inference time, it would be nice if you could load the model in `float16` like in [stable-audio-tools](https://github.com/Stability-AI/stable-audio-tools/blob/main/stable_audio_tools/interface/gradio.py#L51), if you're not using the CPU for inference.

**Comment by Saganaki22** [comment]
Thanks for your suggestion, i have added Half Precision Float 16 Checkbox for Low VRAM usage

**Comment by mamei16** [comment]
Nice, thank you!
